nelmio_api_doc:
    documentation:
        info:
            title: Ecogreen API
            description: Find advices for your garden
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1(?!/doc$) # Accepts routes under /api/v1 except /api/v1/doc
